name: Test

on:
  push:

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.5
    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Run tests
      run: bundle exec rake
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results
